Version: 2.1
/*Plot title*/			Survival
/*Plot type*/			Atoms
/*Y label*/				probability
/*X label*/				Variation_Average
/*Plot File name*/		test_2pic
/*Data set number*/		1
/*Condition number*/	1
/*Picture number*/		2
/*Pixel number*/ 		1
POSITIVE_RESULT_BEGIN
DATA_SET_BEGIN
PICTURE_BEGIN
0
PICTURE_END
PICTURE_BEGIN
0
PICTURE_END
DATA_SET_END
POSITIVE_RESULT_END
POST_SELECTION_BEGIN
CONDITION_BEGIN
DATA_SET_BEGIN
PICTURE_BEGIN
1
PICTURE_END
PICTURE_BEGIN
1
PICTURE_END
DATA_SET_END
CONDITION_END
POST_SELECTION_END
LEGENDS_BEGIN

LEGENDS_END
PLOT_COUNTS_LOCATIONS_BEGIN
PLOT_COUNTS_LOCATIONS_END
FITTING_OPTIONS_BEGIN
-842150451 0
FITTING_OPTIONS_END
HIST_OPTIONS_BEGIN
1
10
HIST_OPTIONS_END
